### ISSUE TITLE
Build is not compiling auth_jwt module

### ISSUE THREAD

**Issue by evertramos** [max-lt/nginx-jwt-module#10]
Hello @maxx-t!

Thanks for sharing this repo. This is what I was looking for to do not need to buy a nginx plus or going for _caddy_.

I ran `./build` and started my container with the following:

```bash
docker run -d --rm --name proxy -v /html/:/var/www/html -v /etc/nginx:/etc/nginx -p "80:80" jwt-nginx
```

In the nginx.conf file I had a very basic settings, but when addind the *auth_jwt* option and reloading nginx I get the message:

```bash
unknown directive "auth_jwt" in /etc/nginx/nginx.conf
```

I just added this options to server block as in README file:

```bash
server {

       auth_jwt_key "9e588fb43b6a1248531156e284c2bea7" hex;
       auth_jwt off;
[...]
```

Could you please confirm if there is anything we must enable before using this directive?

Thanks!

**Comment by maxx-t** [comment]
Hello, sorry for the late answer, I hope you found the solution by yourself.
The first thing to check is if you forgot to add the `load_module /usr/lib/nginx/modules/ngx_http_auth_jwt_module.so;` directive in your nginx.conf file ([example here](https://github.com/maxx-t/nginx-jwt-module/blob/master/test-image/nginx/nginx.conf)).

**Comment by evertramos** [comment]
I found a way around... thanks for the reply though.
