### ISSUE TITLE
jwt parse error

### ISSUE THREAD

**Issue by alexus85** [max-lt/nginx-jwt-module#22]
Hi, 
I'm trying to get this working, but it isn't really clear to me as what format should be the **auth_jwt_key**.
Obviously I'm doing something wrong, cause I'm getting "JWT: failed to parse jwt" error.
 
let's say that my secret key is "HELLO WORLD". What should put into the **auth_jwt_key**? 
just copy & paste the string? Or should I convert it into hex -> "48454c4c4f20574f524c44" 
and then copy it and paste there?

**Comment by alexus85** [comment]
could it be that the auth_jwt_key was too long? cause now that i changed it to just to one word and everything seems to be working now.

**Comment by max-lt** [comment]
Hello,
If your key is "HELLO WORLD" the the directive must be `auth_jwt_key "HELLO WORLD" ;`
If you want to use a hex value as key the directive must be `auth_jwt_key 48454c4c4f20574f524c44 hex ;`

Your error means that your JWT is invalid and cannot be decoded, it looks like this is more a problem with your tokan than with the module. You can use the [jwt.io debbuger](https://jwt.io/) to check your token.
