### ISSUE TITLE
jwt_get_alg(jwt) returns 0

### ISSUE THREAD

**Issue by Mr-Markus** [max-lt/nginx-jwt-module#26]
Hi there,

I am really confused, because I always get 401, because I receive an error that token algorithm is not valid. I found out, that it is always returning 0. My config looks like this

```
location = /jwt/secured {
    auth_jwt on;
    auth_jwt_alg any;
    return 200;
}
```

It happens here:
[https://github.com/max-lt/nginx-jwt-module/blob/master/src/ngx_http_auth_jwt_module.c#L162](https://github.com/max-lt/nginx-jwt-module/blob/master/src/ngx_http_auth_jwt_module.c#L162)

If I comment this block out it works fine

It seems to be an error in jwtlib:
[https://github.com/benmcollins/libjwt/issues/156](https://github.com/benmcollins/libjwt/issues/156)
so a workarround is necessary. Or do you have any other idea?

**Comment by max-lt** [comment]
Hello,
I added some more tests (you can have a look [here](https://github.com/max-lt/nginx-jwt-module/commit/0337442873188517287784b8035f829b0f5f3716?diff=unified#diff-3722d9ba8feb2d3feac8ce71a209a638d4b404e1c53f937188761181594023e2R163-R166)) but I can't reproduce,
could you provide a `curl` command that I can use to reproduce ?

**Comment by max-lt** [comment]
Hello, as I'm writing additional tests for the claim feature, I remembered that the `return` statement is bypassing the jwt module checks.

try with 
```
location = /jwt/secured {
    auth_jwt on;
    auth_jwt_alg any;
    try_files _ @ok;
}

location @ok {
    return 200;
}
```

**Comment by Mr-Markus** [comment]
Hi, good hint and I do not longer receive 200 with that change, but 401 with following message:

```
2022/10/31 07:22:25 [warn] 77#77: *6 JWT: invalid algorithm in jwt 0, client: 172.240.1.1, server: , request: "GET /jwt/secured HTTP/1.1", host: "localhost:7081"

172.240.1.1 - - [31/Oct/2022:07:22:25 +0000] "GET /jwt/secured HTTP/1.1" 401 179 "-" "PostmanRuntime/7.28.4" "-"
```

But my token, that I decoded with jwt.io has following:

```
{
  "alg": "HS256",
  "typ": "JWT",
  "kid": "random-guid"
}
```

Did I miss something?

**Comment by max-lt** [comment]
So weird..
Is `auth_jwt_key` set in your config? (recent update prevents to forgot it)
If you remove `auth_jwt_alg any;` does the token still gets rejected? (it should as JWT_ALG_ANY is default)
