### ISSUE TITLE
(No such file or directory) in /etc/nginx/test-jwt-nginx.conf:41

### ISSUE THREAD

**Issue by shanurrahmanpenny** [max-lt/nginx-jwt-module#27]
I am using this dockerfile to build the image
```
FROM jwt-nginx

# Get nginx ready to run
COPY nginx /etc/nginx

EXPOSE 8000

STOPSIGNAL SIGTERM

CMD ["nginx", "-g", "daemon off;"]
```

build: `docker build -f Dockerfile -t jwt-custom .`
run: `docker container run -p 8080:8000 jwt-custom`

Error
```
...
/docker-entrypoint.sh: Configuration complete; ready for start up
2022/12/29 08:24:24 [error] 1#1: No such file or directory (2: No such file or directory) in /etc/nginx/test-jwt-nginx.conf:41
nginx: [error] No such file or directory (2: No such file or directory) in /etc/nginx/test-jwt-nginx.conf:41
```

I have verified that the file is indeed present in `/etc/nginx` folder

**Comment by shanurrahmanpenny** [comment]
I resolved the issue, what was happening is that some of the key files in `test-jwt-nginx.conf` were missing

**Comment by max-lt** [comment]
Hello, thanks for your inerest, you have to run `make test/keys` to generate new keys ([code here](https://github.com/max-lt/nginx-jwt-module/blob/15a170bf10208ecee74d9a22bf1058b36e6502aa/Makefile#L3))
