### ISSUE TITLE
$jwt_claim_* not set in `rewrite` or `if`

### ISSUE THREAD

**Issue by mechanical-rus528** [max-lt/nginx-jwt-module#30]
Might be related to #28, but doing something like this causes an error:

```
if ($jwt_claim_p != "some_str") {
  return 503;
}
```

This gives me an error in the nginx logs `*1 invalid size ""`.

Similarly you can't use `$jwt_claim_*` in `rewrite` or `proxy_pass` (they're empty), so you cannot use it to verify that the URI is actually allowed to be used, by adding the URI itself as a claim (`$jwt_claim_allowed_uri`). That seems like an important use case of JWTs to me!

**Comment by max-lt** [comment]
I think that's a long-know problem of nginx and ifs, see https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/

**Comment by mechanical-rus528** [comment]
No, it's not just `if`s. Also happens with `rewrite` and `proxy_pass`, but it's a bit harder for me to make a reproducible case with those.

But try it out! E.g. `proxy_pass http://myserver/$jwt_claim_uri`.

I want to use this to give JWT tokens for specific files, e.g. a token so you can only access `/1742712.pdf` for an hour. Is there some way to accomplish that?

**Comment by max-lt** [comment]
Yes the [break](http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#break), [if](http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#if), [return](http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#return), [rewrite](http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#rewrite), and [set](http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#set) directives are processed during [NGX_HTTP_SERVER_REWRITE_PHASE phase](https://nginx.org/en/docs/dev/development_guide.html#http_phases), before this module phases (NGX_HTTP_PREACCESS_PHASE and NGX_HTTP_ACCESS_PHASE), so variables won't be available for these directives.

I don't exacltly know what you're trying to do but if you want to filter a particular user you can use the `auth_jwt_require` of this module that should fit this purpose: 
```nginx
map $jwt_claim_p $jwt_has_some_str_in_claim_p {
    \"some_str\"  1;
}

# ...
server {
  # ...
  location /my-location {
    auth_jwt_require $jwt_has_some_str_in_clain_p error=403;
    # ...
  }
}
```

If you want to map the 403 error to your custom 503 page you can then use named location with the [error_page directive](http://nginx.org/en/docs/http/ngx_http_core_module.html#error_page): 

```nginx
# ...
server {
  # ...

  location @unavailable {
     return 503 "Service unavailable";
  }

  location /my-location {
    error_page 403 = @unavailable;
    auth_jwt_require $jwt_has_some_str_in_clain_p error=403;
   
    # ...
  }
}
