### ISSUE TITLE
 auth_jwt with variables does not work

### ISSUE THREAD

**Issue by zil1** [max-lt/nginx-jwt-module#32]
Hi,
I'm trying to configure the jwt check depending on the request method:
```
http {
...
  map $request_method $jwt_validate {
          POST  on;
          default    off;
  }

  ...
  server {
    auth_jwt off;
    auth_jwt_key /etc/nginx/certs/jwt.pem file;
    ...
    location /api/ {
      auth_jwt $jwt_validate;
      ...
    }
  }
}
```

But I get a 401 response code with any request method

**Comment by max-lt** [comment]
Hello, the `auth_jwt` directive is parsed at config time and cannot be dynamically changed.

**Comment by guanzo** [comment]
Why not let us use dynamic variables though?
