### ISSUE TITLE
Dynamically toggle `auth_jwt`

### ISSUE THREAD

**Issue by guanzo** [max-lt/nginx-jwt-module#34]
`auth_jwt $variable`

Is it possible for the $variable to be `on` or `off`? I tried it and it didn't work but I'm wondering if I can achieve this somehow.

**Comment by guanzo** [comment]
Managed to implement this with njs and internal redirects. 

If no jwt then redirect to @no_auth named location, otherwise redirect to @with_auth named location.

**Comment by max-lt** [comment]
Yeah I think this this the only way as auth_jwt is parsed once during server configuration.
