### ISSUE TITLE
Enhancement - Optional Login Redirect

### ISSUE THREAD

**Issue by bradleymize** [max-lt/nginx-jwt-module#35]
Would it be possible to add something like in https://github.com/TeslaGov/ngx-http-auth-jwt-module to have an optional `auth_jwt_redirect` / `auth_jwt_loginurl` to redirect if no jwt is present?

Example: Without `auth_jwt_redirect` / `auth_jwt_loginurl` (existing behavior / new configuration option but unconfigured by default)
- User navigates to secured site without a jwt = 401

Example: With `auth_jwt_redirect "on"` + `auth_jwt_loginurl: "<url>"` (new behavior)
- User navigates to secured site without a jwt = redirects to the login page/site to login with some query string for returning back to the site (e.g. `?returnUrl=<secured site>`)

This would allow for a server configuration like:

```nginx
auth_jwt_key "<secret hex string>";
auth_jwt_alg "HS256";
auth_jwt_loginurl "https://login.example.com/";

location / {
    auth_jwt_redirect "on";
    auth_jwt $cookie_jwt_token;
    auth_jwt_require $jwt_has_status_permission error=403;

    proxy_pass                          http://192.168.68.71:6000/;
    # etc...
}

location /api {
    auth_jwt_redirect "off"; #disable login redirect when accessing a programmatic endpoint
}
```

And when someone visits `status.example.com` without a JWT, they're redirected to login at `https://login.example.com/?returnUrl=https://status.example.com`. (I'm using https://github.com/qvest-digital/loginsrv as a simple authentication proxy)

After returning to `status.example.com`, it'll then check to see if they have the `status` permission/claim (implied by `$jwt_has_status_permission`).

(Optionally have some sort of `auth_jwt_loginurl_query_param_name` to configure the `returnUrl` parameter if it needs to be something different, however Loginsrv supports changing what query param to look for, however other solutions might not be as flexible, so this would aid making this enhancement more widely useable)

**Comment by max-lt** [comment]
No, actually it was one of the reason why I moved from TeslaGov's module iirc https://github.com/TeslaGov/ngx-http-auth-jwt-module/issues/37 and started this one. 

You don't need `auth_jwt_redirect` and can use `error_page` directive and named locations instead : 

```
location @login_err_redirect {
    return 302 https://example.com?redirect=$request_uri&$args;
}

location ~ ^/secure/ {
    auth_jwt on;
    error_page 401 = @login_err_redirect;
}
```

Didn't try with this one tho, i'd be interested to know if you make it works (even more if you don't) so I can add it to the documentation.

**Comment by max-lt** [comment]
Just tried, it it works as expected: 

```nginx nginx.conf
load_module /usr/lib/nginx/modules/ngx_http_auth_jwt_module.so;

user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    server {
        listen 7890;
        server_name _;

        auth_jwt_key "0123456789abcdef" hex; # Your key as hex string
        auth_jwt     off;

        location @login_err_redirect {
            return 302 $scheme://$host:$server_port/login?redirect=$request_uri;
        }

        location /secure/ {
            auth_jwt on;
            error_page 401 = @login_err_redirect;
        }

        location / {
        return 200 "OK";
        }
    }
}
```

```bash
docker run -v ./nginx.conf:/etc/nginx/nginx.conf -p 7890:7890  ghcr.io/max-lt/nginx-jwt-module:v3.4.1
```

`/secure/path?a=3&u=12` redirects to `/login?redirect=/secure/path?a=3&u=12`

**Comment by bradleymize** [comment]
Confirmed that works:
```nginx
location @login_err_redirect {
    return 302 https://login.example.com/?return_url=https://$host$request_uri;
}

location / {
    auth_jwt $cookie_jwt_token;
    auth_jwt_require $jwt_has_status_permission error=403;
    error_page 401 = @login_err_redirect;

    #etc...
}
```
(my use-case is an authentication + authorization reverse proxy, as a more user-friendly alternative to client certificates)

Something I'll have to double check after work now that I have this working is verify if the claims allowed for uppercase, but when I initially tested, it didn't like when one of the claims was `AllowedSites`, e.g.

`AllowedSites: "status,other"`

It would show up in `add_header DBG-COOKIE-PAYLOAD $jwt_payload` but everything would stop working when I tried `$jwt_claim_AllowedSites`

**Comment by max-lt** [comment]
Indeed it wont work, [when Nginx attempts to resolve a name it actually forces the name to lower case](https://stackoverflow.com/a/57718315/4111143). Source can be found [here](https://github.com/nginx/nginx/blob/8e2949e56a13405a157e05b21aa4c4a5fa468335/src/core/ngx_resolver.c#L594).

**Comment by bradleymize** [comment]
Didn't know about either of those, thanks for the links to the source/documentation, I appreciate it

Confirmed it worked with `allowed_sites` and using a regex comparison in the `map` block
```nginx
# e.g. allowed_sites: "status,other"
map $jwt_claim_allowed_sites $jwt_has_status_permission {
    "~.*status.*"  1;
}
```
