### ISSUE TITLE
auth_jwt_require against nginx embedded variable?

### ISSUE THREAD

**Issue by slushpuppy** [max-lt/nginx-jwt-module#37]
Hi,

     I am looking for a way to verify jwt claims against a dynamic runtime nginx embedded variable, e.g. cookie or uri? is that a possibility? I have tried using map regex trick but nginx server crashes which leads me to believe it isn't a supported feature

Thanks

**Comment by max-lt** [comment]
Hi, this is a possibility, you can find an example un the documentation. Can you post your configuration and the crash log please?
